package com.example.aimodgen.item;

import com.example.aimodgen.generation.GeneratedContent;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.TooltipFlag;
import net.minecraft.world.level.Level;
import org.jetbrains.annotations.Nullable;

import java.util.List;

public class AIGeneratedItem extends Item {
    private GeneratedContent content;

    public AIGeneratedItem(Properties properties, GeneratedContent content) {
        super(properties);
        this.content = content;
    }

    public void setGeneratedContent(GeneratedContent content) {
        this.content = content;
    }    @Override
    public void appendHoverText(ItemStack stack, @Nullable Level level, List<Component> tooltip, TooltipFlag flag) {
        super.appendHoverText(stack, level, tooltip, flag);
        tooltip.add(Component.literal("§7Generated by AI"));
        if (content != null && content.getDescription() != null && !content.getDescription().isEmpty()) {
            tooltip.add(Component.literal("§9" + content.getDescription()));
        }
    }

    public GeneratedContent getContent() {
        return content;
    }
}
